import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedBooks() {
    const books = [
        {
            title: "O Senhor dos Anéis",
            author: "J.R.R. Tolkien",
            isbn: "9780544003415",
            category: "Fantasia",
            publisher: "HarperCollins",
            publicationYear: 1954,
            totalQuantity: 5,
            quantityAvailable: 5,
            coverUrl: "https://exemplo.com/lotr.jpg",
        },
        {
            title: "O Hobbit",
            author: "J.R.R. Tolkien",
            isbn: "9780007458424",
            category: "Fantasia",
            publisher: "HarperCollins",
            publicationYear: 1937,
            totalQuantity: 4,
            quantityAvailable: 4,
            coverUrl: "https://exemplo.com/hobbit.jpg",
        },
        {
            title: "As Crônicas de Nárnia",
            author: "C.S. Lewis",
            isbn: "9780066238500",
            category: "Fantasia",
            publisher: "HarperCollins",
            publicationYear: 1950,
            totalQuantity: 6,
            quantityAvailable: 6,
            coverUrl: "https://exemplo.com/narnia.jpg",
        },
        {
            title: "Clean Architecture",
            author: "Robert C. Martin",
            isbn: "9780134494166",
            category: "Tecnologia",
            publisher: "Prentice Hall",
            publicationYear: 2017,
            totalQuantity: 3,
            quantityAvailable: 3,
            coverUrl: "https://exemplo.com/clean-arch.jpg",
        },
        {
            title: "Refactoring",
            author: "Martin Fowler",
            isbn: "9780201485677",
            category: "Tecnologia",
            publisher: "Addison-Wesley",
            publicationYear: 1999,
            totalQuantity: 3,
            quantityAvailable: 3,
            coverUrl: "https://exemplo.com/refactoring.jpg",
        },
        {
            title: "Design Patterns",
            author: "Erich Gamma et al.",
            isbn: "9780201633610",
            category: "Tecnologia",
            publisher: "Addison-Wesley",
            publicationYear: 1994,
            totalQuantity: 2,
            quantityAvailable: 2,
            coverUrl: "https://exemplo.com/design-patterns.jpg",
        },
        {
            title: "Duna",
            author: "Frank Herbert",
            isbn: "9780441172719",
            category: "Ficção Científica",
            publisher: "Ace Books",
            publicationYear: 1965,
            totalQuantity: 5,
            quantityAvailable: 5,
            coverUrl: "https://exemplo.com/duna.jpg",
        },
        {
            title: "Neuromancer",
            author: "William Gibson",
            isbn: "9780441569595",
            category: "Ficção Científica",
            publisher: "Ace Books",
            publicationYear: 1984,
            totalQuantity: 3,
            quantityAvailable: 3,
            coverUrl: "https://exemplo.com/neuromancer.jpg",
        },
        {
            title: "Orgulho e Preconceito",
            author: "Jane Austen",
            isbn: "9780141439518",
            category: "Romance",
            publisher: "Penguin",
            publicationYear: 1813,
            totalQuantity: 4,
            quantityAvailable: 4,
            coverUrl: "https://exemplo.com/orgulho.jpg",
        },
        {
            title: "Dom Casmurro",
            author: "Machado de Assis",
            isbn: "9788520927074",
            category: "Romance",
            publisher: "Nova Fronteira",
            publicationYear: 1899,
            totalQuantity: 5,
            quantityAvailable: 5,
            coverUrl: "https://exemplo.com/domcasmurro.jpg",
        },
    ];

    await prisma.book.createMany({ data: books, skipDuplicates: true });
    console.log("📚 Livros de exemplo criados");
}
